<?php
$jieqiBlocks['0'] = array (
  'bid' => '106',
  'blockname' => '广告980x90',
  'module' => 'article',
  'filename' => '',
  'classname' => 'BlockSystemCustom',
  'side' => '-1',
  'title' => '',
  'vars' => '',
  'template' => '',
  'contenttype' => '1',
  'custom' => '1',
  'publish' => '3',
  'hasvars' => '0',
);
$jieqiBlocks['1'] = array (
  'bid' => '105',
  'blockname' => '成神之路',
  'module' => 'article',
  'filename' => 'block_commend',
  'classname' => 'BlockArticleCommend',
  'side' => '0',
  'title' => '成神之路',
  'vars' => '6|7|8|9|10',
  'template' => 'ruoxia_list1.html',
  'contenttype' => '1',
  'custom' => '0',
  'publish' => '3',
  'hasvars' => '2',
);
$jieqiBlocks['2'] = array (
  'bid' => '1',
  'blockname' => '本站公告',
  'module' => 'system',
  'filename' => '',
  'classname' => 'BlockSystemCustom',
  'side' => '4',
  'title' => '本站公告',
  'vars' => '',
  'template' => '',
  'contenttype' => '1',
  'custom' => '1',
  'publish' => '3',
  'hasvars' => '0',
);
$jieqiBlocks['3'] = array (
  'bid' => '2',
  'blockname' => '用户登录',
  'module' => 'system',
  'filename' => 'block_login',
  'classname' => 'BlockSystemLogin',
  'side' => '0',
  'title' => '用户登录',
  'vars' => '',
  'template' => '',
  'contenttype' => '4',
  'custom' => '0',
  'publish' => '3',
  'hasvars' => '0',
);
$jieqiBlocks['4'] = array (
  'bid' => '103',
  'blockname' => '新闻类别列表',
  'module' => 'news',
  'filename' => 'block_newsclass',
  'classname' => 'BlockNewsClass',
  'side' => '0',
  'title' => '新闻类别',
  'vars' => '16,5',
  'template' => 'block_newsclass.html',
  'contenttype' => '1',
  'custom' => '0',
  'publish' => '3',
  'hasvars' => '1',
);
$jieqiBlocks['5'] = array (
  'bid' => '63',
  'blockname' => '友情链接',
  'module' => 'link',
  'filename' => 'block_linklist',
  'classname' => 'BlockLinkLinklist',
  'side' => '8',
  'title' => '友情链接',
  'vars' => '10,2,0,64',
  'template' => 'block_linklist.html',
  'contenttype' => '1',
  'custom' => '0',
  'publish' => '3',
  'hasvars' => '1',
);
$jieqiBlocks['6'] = array (
  'bid' => '47',
  'blockname' => '小说封面推荐',
  'module' => 'article',
  'filename' => 'block_commend',
  'classname' => 'BlockArticleCommend',
  'side' => '5',
  'title' => '封面推荐',
  'vars' => '1|2|3|6',
  'template' => 'block_commend.html',
  'contenttype' => '1',
  'custom' => '0',
  'publish' => '3',
  'hasvars' => '2',
);

?>